Fix fuzzers build
- the HttpEcho build broke with commit
  08d9081280f80094194bd8501030fdd2e6dde6af (net: don't try to set
  TCP_NODELAY on local Unix sockets., 2023-10-30)

- fix an unused variable error from commit
  0631593c96289de2cc26d8efdfd6155547fe740c (wasm: proxy wopi documents,
  2023-11-06).

- the undefined reference to OXOOLWSD::ForKitProcId probably went wrong
  in commit 3f46c1db445b9840318af0a4994f0c3ff1012285 (kit-in-process:
  pure re-factor to a run-time function to flag this., 2023-11-20)

Signed-off-by: Miklos Vajna <vmiklos@collabora.com>
Change-Id: I0cf06d188860bdb2f795485a91c7634b596255aa